# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=20)),
                ('curdate', models.DateTimeField()),
                ('feedbackscore', models.IntegerField()),
            ],
        ),
    ]
