# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_product_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
