# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20160927_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='galleryurl',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
