# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20160927_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='galleryurl',
            field=models.CharField(max_length=250),
        ),
    ]
