# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20160927_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='curdate',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
