# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20160927_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='curdate',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='starttime',
            field=models.CharField(max_length=35),
        ),
    ]
