# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20160927_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='curdate',
            new_name='credate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='starttime',
            new_name='startttime',
        ),
    ]
