# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20160927_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='credate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='startttime',
        ),
        migrations.AddField(
            model_name='product',
            name='cdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='starttime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
