# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20160928_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cdate',
            new_name='curdate',
        ),
    ]
