# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20160928_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='curdate',
            field=models.DateField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='starttime',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
