# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20160928_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='curdate',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='starttime',
            field=models.DateTimeField(default=0),
        ),
    ]
