# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20160928_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='curdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 28, 8, 48, 42, 61000)),
        ),
        migrations.AlterField(
            model_name='product',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 28, 8, 48, 42, 61000)),
        ),
    ]
