# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20160928_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='curdate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='starttime',
        ),
    ]
