# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20160928_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='curdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
