# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=5)),
                ('hitcounter', models.CharField(max_length=20)),
                ('itemid', models.CharField(max_length=20)),
                ('starttime', models.DateTimeField(null=True)),
                ('viewitemurl', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=20)),
                ('categoryid', models.CharField(max_length=8)),
                ('feedbackscore', models.CharField(max_length=9)),
                ('usersite', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=40)),
                ('storeowner', models.CharField(max_length=6)),
                ('currentprice', models.CharField(max_length=7)),
                ('quantitysold', models.CharField(max_length=6)),
                ('quantitysoldinstore', models.CharField(max_length=4)),
                ('shippingservice', models.CharField(max_length=50)),
                ('shippingcost', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('hitcount', models.CharField(max_length=12)),
                ('sku', models.CharField(max_length=13)),
                ('galleryurl', models.CharField(max_length=250)),
                ('listduration', models.CharField(max_length=20)),
                ('privatelisting', models.CharField(max_length=5)),
                ('curdate', models.DateTimeField(null=True)),
                ('deltatitle', models.CharField(max_length=5)),
                ('deltasold', models.CharField(max_length=6)),
                ('deltahit', models.CharField(max_length=6)),
                ('deltaprice', models.CharField(max_length=6)),
                ('listingstatus', models.CharField(max_length=20)),
                ('deltadays', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
    ]
