# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160928_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mysku',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
