# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_shops_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=20)),
                ('curdate', models.DateTimeField()),
                ('updatetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
