# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_kwproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwproducts',
            name='keywords',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kwproducts',
            name='mysku',
            field=models.CharField(max_length=20),
        ),
    ]
